# qte56_dialogs.pro — merged DLL (auto-generated by merge_dlls.py)
# Modules: qdialog, qmessagebox, qfiledialog, qinputdialog, qfontdialog, qcolordialog, qprogressdialog
#

QT       += core widgets
TARGET    = qte56_dialogs
TEMPLATE  = lib
CONFIG   += shared c++11
CONFIG   -= debug_and_release

DEFINES  += \
    QTE56_QDIALOG_BUILD \
    QTE56_QMESSAGEBOX_BUILD \
    QTE56_QFILEDIALOG_BUILD \
    QTE56_QINPUTDIALOG_BUILD \
    QTE56_QFONTDIALOG_BUILD \
    QTE56_QCOLORDIALOG_BUILD \
    QTE56_QPROGRESSDIALOG_BUILD

INCLUDEPATH += \
    ../../qte56_qdialog \
    ../../qte56_qmessagebox \
    ../../qte56_qfiledialog \
    ../../qte56_qinputdialog \
    ../../qte56_qfontdialog \
    ../../qte56_qcolordialog \
    ../../qte56_qprogressdialog

SOURCES  += \
    ../../qte56_qdialog/qte56_qdialog.cpp \
    ../../qte56_qmessagebox/qte56_qmessagebox.cpp \
    ../../qte56_qfiledialog/qte56_qfiledialog.cpp \
    ../../qte56_qinputdialog/qte56_qinputdialog.cpp \
    ../../qte56_qfontdialog/qte56_qfontdialog.cpp \
    ../../qte56_qcolordialog/qte56_qcolordialog.cpp \
    ../../qte56_qprogressdialog/qte56_qprogressdialog.cpp

HEADERS  += \
    ../../qte56_qdialog/qte56_qdialog.h \
    ../../qte56_qmessagebox/qte56_qmessagebox.h \
    ../../qte56_qfiledialog/qte56_qfiledialog.h \
    ../../qte56_qinputdialog/qte56_qinputdialog.h \
    ../../qte56_qfontdialog/qte56_qfontdialog.h \
    ../../qte56_qcolordialog/qte56_qcolordialog.h \
    ../../qte56_qprogressdialog/qte56_qprogressdialog.h

# Выбор папки назначения по QTE56_ARCH (32 или 64)
# Настройка компилятора через PATH (a.cmd)
QTE56_ARCH = $$(QTE56_ARCH)
isEmpty(QTE56_ARCH) {
    QTE56_ARCH = 32
}

equals(QTE56_ARCH, 64) {
    DESTDIR = ../../../../dll/dll64
} else {
    DESTDIR = ../../../../dll/dll32
}

unix: DESTDIR = ../../../../lib

macx {
    # macx-clang mkspec включает -fvisibility=hidden глобально —
    # переопределяем чтобы extern "C" функции были видны в dylib
    QMAKE_CXXFLAGS += -fvisibility=default
    QMAKE_CFLAGS   += -fvisibility=default
}
