# qte56_widgets.pro — merged DLL (auto-generated by merge_dlls.py)
# Modules: qwidget, qframe, qlabel, qpushbutton, qcheckbox, qradiobutton, qcombobox, qlineedit, qspinbox, qdoublespinbox, qslider, qdial, qscrollbar, qprogressbar, qgroupbox, qtabwidget, qtabbar, qlcdnumber, qcalendarwidget, qlayout, qabstractbutton, qabstractslider, qabstractspinbox, qsplitter, qstackedwidget, qdatetimeedit
#

QT       += core widgets
TARGET    = qte56_widgets
TEMPLATE  = lib
CONFIG   += shared c++11
CONFIG   -= debug_and_release

DEFINES  += \
    QTE56_QWIDGET_BUILD \
    QTE56_QFRAME_BUILD \
    QTE56_QLABEL_BUILD \
    QTE56_QPUSHBUTTON_BUILD \
    QTE56_QCHECKBOX_BUILD \
    QTE56_QRADIOBUTTON_BUILD \
    QTE56_QCOMBOBOX_BUILD \
    QTE56_QLINEEDIT_BUILD \
    QTE56_QSPINBOX_BUILD \
    QTE56_QDOUBLESPINBOX_BUILD \
    QTE56_QSLIDER_BUILD \
    QTE56_QDIAL_BUILD \
    QTE56_QSCROLLBAR_BUILD \
    QTE56_QPROGRESSBAR_BUILD \
    QTE56_QGROUPBOX_BUILD \
    QTE56_QTABWIDGET_BUILD \
    QTE56_QTABBAR_BUILD \
    QTE56_QLCDNUMBER_BUILD \
    QTE56_QCALENDARWIDGET_BUILD \
    QTE56_QLAYOUT_BUILD \
    QTE56_QABSTRACTBUTTON_BUILD \
    QTE56_QABSTRACTSLIDER_BUILD \
    QTE56_QABSTRACTSPINBOX_BUILD \
    QTE56_QSPLITTER_BUILD \
    QTE56_QSTACKEDWIDGET_BUILD \
    QTE56_QDATETIMEEDIT_BUILD \
    QTE56_QTEXTDOCUMENT_BUILD

INCLUDEPATH += \
    ../../qte56_qwidget \
    ../../qte56_qframe \
    ../../qte56_qlabel \
    ../../qte56_qpushbutton \
    ../../qte56_qcheckbox \
    ../../qte56_qradiobutton \
    ../../qte56_qcombobox \
    ../../qte56_qlineedit \
    ../../qte56_qspinbox \
    ../../qte56_qdoublespinbox \
    ../../qte56_qslider \
    ../../qte56_qdial \
    ../../qte56_qscrollbar \
    ../../qte56_qprogressbar \
    ../../qte56_qgroupbox \
    ../../qte56_qtabwidget \
    ../../qte56_qtabbar \
    ../../qte56_qlcdnumber \
    ../../qte56_qcalendarwidget \
    ../../qte56_qlayout \
    ../../qte56_qabstractbutton \
    ../../qte56_qabstractslider \
    ../../qte56_qabstractspinbox \
    ../../qte56_qsplitter \
    ../../qte56_qstackedwidget \
    ../../qte56_qdatetimeedit \
    ../../qte56_qtextdocument

SOURCES  += \
    ../../qte56_qwidget/qte56_qwidget.cpp \
    ../../qte56_qframe/qte56_qframe.cpp \
    ../../qte56_qlabel/qte56_qlabel.cpp \
    ../../qte56_qpushbutton/qte56_qpushbutton.cpp \
    ../../qte56_qcheckbox/qte56_qcheckbox.cpp \
    ../../qte56_qradiobutton/qte56_qradiobutton.cpp \
    ../../qte56_qcombobox/qte56_qcombobox.cpp \
    ../../qte56_qlineedit/qte56_qlineedit.cpp \
    ../../qte56_qspinbox/qte56_qspinbox.cpp \
    ../../qte56_qdoublespinbox/qte56_qdoublespinbox.cpp \
    ../../qte56_qslider/qte56_qslider.cpp \
    ../../qte56_qdial/qte56_qdial.cpp \
    ../../qte56_qscrollbar/qte56_qscrollbar.cpp \
    ../../qte56_qprogressbar/qte56_qprogressbar.cpp \
    ../../qte56_qgroupbox/qte56_qgroupbox.cpp \
    ../../qte56_qtabwidget/qte56_qtabwidget.cpp \
    ../../qte56_qtabbar/qte56_qtabbar.cpp \
    ../../qte56_qlcdnumber/qte56_qlcdnumber.cpp \
    ../../qte56_qcalendarwidget/qte56_qcalendarwidget.cpp \
    ../../qte56_qlayout/qte56_qlayout.cpp \
    ../../qte56_qabstractbutton/qte56_qabstractbutton.cpp \
    ../../qte56_qabstractslider/qte56_qabstractslider.cpp \
    ../../qte56_qabstractspinbox/qte56_qabstractspinbox.cpp \
    ../../qte56_qsplitter/qte56_qsplitter.cpp \
    ../../qte56_qstackedwidget/qte56_qstackedwidget.cpp \
    ../../qte56_qdatetimeedit/qte56_qdatetimeedit.cpp \
    ../../qte56_qtextdocument/qte56_qtextdocument.cpp

HEADERS  += \
    ../../qte56_qwidget/qte56_qwidget.h \
    ../../qte56_qframe/qte56_qframe.h \
    ../../qte56_qlabel/qte56_qlabel.h \
    ../../qte56_qpushbutton/qte56_qpushbutton.h \
    ../../qte56_qcheckbox/qte56_qcheckbox.h \
    ../../qte56_qradiobutton/qte56_qradiobutton.h \
    ../../qte56_qcombobox/qte56_qcombobox.h \
    ../../qte56_qlineedit/qte56_qlineedit.h \
    ../../qte56_qspinbox/qte56_qspinbox.h \
    ../../qte56_qdoublespinbox/qte56_qdoublespinbox.h \
    ../../qte56_qslider/qte56_qslider.h \
    ../../qte56_qdial/qte56_qdial.h \
    ../../qte56_qscrollbar/qte56_qscrollbar.h \
    ../../qte56_qprogressbar/qte56_qprogressbar.h \
    ../../qte56_qgroupbox/qte56_qgroupbox.h \
    ../../qte56_qtabwidget/qte56_qtabwidget.h \
    ../../qte56_qtabbar/qte56_qtabbar.h \
    ../../qte56_qlcdnumber/qte56_qlcdnumber.h \
    ../../qte56_qcalendarwidget/qte56_qcalendarwidget.h \
    ../../qte56_qlayout/qte56_qlayout.h \
    ../../qte56_qabstractbutton/qte56_qabstractbutton.h \
    ../../qte56_qabstractslider/qte56_qabstractslider.h \
    ../../qte56_qabstractspinbox/qte56_qabstractspinbox.h \
    ../../qte56_qsplitter/qte56_qsplitter.h \
    ../../qte56_qstackedwidget/qte56_qstackedwidget.h \
    ../../qte56_qdatetimeedit/qte56_qdatetimeedit.h \
    ../../qte56_qtextdocument/qte56_qtextdocument.h

# Выбор папки назначения по QTE56_ARCH (32 или 64)
# Настройка компилятора через PATH (a.cmd)
QTE56_ARCH = $$(QTE56_ARCH)
isEmpty(QTE56_ARCH) {
    QTE56_ARCH = 32
}

equals(QTE56_ARCH, 64) {
    DESTDIR = ../../../../dll/dll64
} else {
    DESTDIR = ../../../../dll/dll32
}

unix: DESTDIR = ../../../../lib

macx {
    # macx-clang mkspec включает -fvisibility=hidden глобально —
    # переопределяем чтобы extern "C" функции были видны в dylib
    QMAKE_CXXFLAGS += -fvisibility=default
    QMAKE_CFLAGS   += -fvisibility=default
}
