# qte56_text.pro — merged DLL (auto-generated by merge_dlls.py)
# Modules: qplaintextedit, qtextedit, qtextbrowser, qtextcursor, qtextcharformat, qtextblockformat, qtextblock, qsyntaxhighlighter
#

QT       += core gui widgets
TARGET    = qte56_text
TEMPLATE  = lib
CONFIG   += shared c++11
CONFIG   -= debug_and_release

DEFINES  += \
    QTE56_QPLAINTEXTEDIT_BUILD \
    QTE56_QTEXTEDIT_BUILD \
    QTE56_QTEXTBROWSER_BUILD \
    QTE56_QTEXTCURSOR_BUILD \
    QTE56_QTEXTCHARFORMAT_BUILD \
    QTE56_QTEXTBLOCKFORMAT_BUILD \
    QTE56_QTEXTBLOCK_BUILD \
    QTE56_QSYNTAXHIGHLIGHTER_BUILD

INCLUDEPATH += \
    ../../qte56_qplaintextedit \
    ../../qte56_qtextedit \
    ../../qte56_qtextbrowser \
    ../../qte56_qtextcursor \
    ../../qte56_qtextcharformat \
    ../../qte56_qtextblockformat \
    ../../qte56_qtextblock \
    ../../qte56_qsyntaxhighlighter

SOURCES  += \
    ../../qte56_qplaintextedit/qte56_qplaintextedit.cpp \
    ../../qte56_qtextedit/qte56_qtextedit.cpp \
    ../../qte56_qtextbrowser/qte56_qtextbrowser.cpp \
    ../../qte56_qtextcursor/qte56_qtextcursor.cpp \
    ../../qte56_qtextcharformat/qte56_qtextcharformat.cpp \
    ../../qte56_qtextblockformat/qte56_qtextblockformat.cpp \
    ../../qte56_qtextblock/qte56_qtextblock.cpp \
    ../../qte56_qsyntaxhighlighter/qte56_qsyntaxhighlighter.cpp

HEADERS  += \
    ../../qte56_qplaintextedit/qte56_qplaintextedit.h \
    ../../qte56_qtextedit/qte56_qtextedit.h \
    ../../qte56_qtextbrowser/qte56_qtextbrowser.h \
    ../../qte56_qtextcursor/qte56_qtextcursor.h \
    ../../qte56_qtextcharformat/qte56_qtextcharformat.h \
    ../../qte56_qtextblockformat/qte56_qtextblockformat.h \
    ../../qte56_qtextblock/qte56_qtextblock.h \
    ../../qte56_qsyntaxhighlighter/qte56_qsyntaxhighlighter.h

# Выбор папки назначения по QTE56_ARCH (32 или 64)
# Настройка компилятора через PATH (a.cmd)
QTE56_ARCH = $$(QTE56_ARCH)
isEmpty(QTE56_ARCH) {
    QTE56_ARCH = 32
}

equals(QTE56_ARCH, 64) {
    DESTDIR = ../../../../dll/dll64
} else {
    DESTDIR = ../../../../dll/dll32
}

unix: DESTDIR = ../../../../lib

macx {
    # macx-clang mkspec включает -fvisibility=hidden глобально —
    # переопределяем чтобы extern "C" функции были видны в dylib
    QMAKE_CXXFLAGS += -fvisibility=default
    QMAKE_CFLAGS   += -fvisibility=default
}
