# qte56_views.pro — merged DLL (auto-generated by merge_dlls.py)
# Modules: qabstractscrollarea, qabstractitemview, qscrollarea, qlistwidget, qtableview, qtablewidget, qtreeview, qtreewidget, qheaderview, qmdiarea, qmdisubwindow
#

QT       += core widgets
TARGET    = qte56_views
TEMPLATE  = lib
CONFIG   += shared c++11
CONFIG   -= debug_and_release

DEFINES  += \
    QTE56_QABSTRACTSCROLLAREA_BUILD \
    QTE56_QABSTRACTITEMVIEW_BUILD \
    QTE56_QSCROLLAREA_BUILD \
    QTE56_QLISTWIDGET_BUILD \
    QTE56_QTABLEVIEW_BUILD \
    QTE56_QTABLEWIDGET_BUILD \
    QTE56_QTREEVIEW_BUILD \
    QTE56_QTREEWIDGET_BUILD \
    QTE56_QHEADERVIEW_BUILD \
    QTE56_QMDIAREA_BUILD \
    QTE56_QMDISUBWINDOW_BUILD

INCLUDEPATH += \
    ../../qte56_qabstractscrollarea \
    ../../qte56_qabstractitemview \
    ../../qte56_qscrollarea \
    ../../qte56_qlistwidget \
    ../../qte56_qtableview \
    ../../qte56_qtablewidget \
    ../../qte56_qtreeview \
    ../../qte56_qtreewidget \
    ../../qte56_qheaderview \
    ../../qte56_qmdiarea \
    ../../qte56_qmdisubwindow

SOURCES  += \
    ../../qte56_qabstractscrollarea/qte56_qabstractscrollarea.cpp \
    ../../qte56_qabstractitemview/qte56_qabstractitemview.cpp \
    ../../qte56_qscrollarea/qte56_qscrollarea.cpp \
    ../../qte56_qlistwidget/qte56_qlistwidget.cpp \
    ../../qte56_qtableview/qte56_qtableview.cpp \
    ../../qte56_qtablewidget/qte56_qtablewidget.cpp \
    ../../qte56_qtreeview/qte56_qtreeview.cpp \
    ../../qte56_qtreewidget/qte56_qtreewidget.cpp \
    ../../qte56_qheaderview/qte56_qheaderview.cpp \
    ../../qte56_qmdiarea/qte56_qmdiarea.cpp \
    ../../qte56_qmdisubwindow/qte56_qmdisubwindow.cpp

HEADERS  += \
    ../../qte56_qabstractscrollarea/qte56_qabstractscrollarea.h \
    ../../qte56_qabstractitemview/qte56_qabstractitemview.h \
    ../../qte56_qscrollarea/qte56_qscrollarea.h \
    ../../qte56_qlistwidget/qte56_qlistwidget.h \
    ../../qte56_qtableview/qte56_qtableview.h \
    ../../qte56_qtablewidget/qte56_qtablewidget.h \
    ../../qte56_qtreeview/qte56_qtreeview.h \
    ../../qte56_qtreewidget/qte56_qtreewidget.h \
    ../../qte56_qheaderview/qte56_qheaderview.h \
    ../../qte56_qmdiarea/qte56_qmdiarea.h \
    ../../qte56_qmdisubwindow/qte56_qmdisubwindow.h

# Выбор папки назначения по QTE56_ARCH (32 или 64)
# Настройка компилятора через PATH (a.cmd)
QTE56_ARCH = $$(QTE56_ARCH)
isEmpty(QTE56_ARCH) {
    QTE56_ARCH = 32
}

equals(QTE56_ARCH, 64) {
    DESTDIR = ../../../../dll/dll64
} else {
    DESTDIR = ../../../../dll/dll32
}

unix: DESTDIR = ../../../../lib

macx {
    # macx-clang mkspec включает -fvisibility=hidden глобально —
    # переопределяем чтобы extern "C" функции были видны в dylib
    QMAKE_CXXFLAGS += -fvisibility=default
    QMAKE_CFLAGS   += -fvisibility=default
}
