# qte56_mainwin.pro — merged DLL (auto-generated by merge_dlls.py)
# Modules: qmainwindow, qmenubar, qmenu, qaction, qtoolbar, qtoolbutton, qcommandlinkbutton, qstatusbar, qdockwidget, qtoolbox
#

QT       += core widgets
TARGET    = qte56_mainwin
TEMPLATE  = lib
CONFIG   += shared c++11
CONFIG   -= debug_and_release

DEFINES  += \
    QTE56_QMAINWINDOW_BUILD \
    QTE56_QMENUBAR_BUILD \
    QTE56_QMENU_BUILD \
    QTE56_QACTION_BUILD \
    QTE56_QTOOLBAR_BUILD \
    QTE56_QTOOLBUTTON_BUILD \
    QTE56_QCOMMANDLINKBUTTON_BUILD \
    QTE56_QSTATUSBAR_BUILD \
    QTE56_QDOCKWIDGET_BUILD \
    QTE56_QTOOLBOX_BUILD

INCLUDEPATH += \
    ../../qte56_qmainwindow \
    ../../qte56_qmenubar \
    ../../qte56_qmenu \
    ../../qte56_qaction \
    ../../qte56_qtoolbar \
    ../../qte56_qtoolbutton \
    ../../qte56_qcommandlinkbutton \
    ../../qte56_qstatusbar \
    ../../qte56_qdockwidget \
    ../../qte56_qtoolbox

SOURCES  += \
    ../../qte56_qmainwindow/qte56_qmainwindow.cpp \
    ../../qte56_qmenubar/qte56_qmenubar.cpp \
    ../../qte56_qmenu/qte56_qmenu.cpp \
    ../../qte56_qaction/qte56_qaction.cpp \
    ../../qte56_qtoolbar/qte56_qtoolbar.cpp \
    ../../qte56_qtoolbutton/qte56_qtoolbutton.cpp \
    ../../qte56_qcommandlinkbutton/qte56_qcommandlinkbutton.cpp \
    ../../qte56_qstatusbar/qte56_qstatusbar.cpp \
    ../../qte56_qdockwidget/qte56_qdockwidget.cpp \
    ../../qte56_qtoolbox/qte56_qtoolbox.cpp

HEADERS  += \
    ../../qte56_qmainwindow/qte56_qmainwindow.h \
    ../../qte56_qmenubar/qte56_qmenubar.h \
    ../../qte56_qmenu/qte56_qmenu.h \
    ../../qte56_qaction/qte56_qaction.h \
    ../../qte56_qtoolbar/qte56_qtoolbar.h \
    ../../qte56_qtoolbutton/qte56_qtoolbutton.h \
    ../../qte56_qcommandlinkbutton/qte56_qcommandlinkbutton.h \
    ../../qte56_qstatusbar/qte56_qstatusbar.h \
    ../../qte56_qdockwidget/qte56_qdockwidget.h \
    ../../qte56_qtoolbox/qte56_qtoolbox.h

# Выбор папки назначения по QTE56_ARCH (32 или 64)
# Настройка компилятора через PATH (a.cmd)
QTE56_ARCH = $$(QTE56_ARCH)
isEmpty(QTE56_ARCH) {
    QTE56_ARCH = 32
}

equals(QTE56_ARCH, 64) {
    DESTDIR = ../../../../dll/dll64
} else {
    DESTDIR = ../../../../dll/dll32
}

unix: DESTDIR = ../../../../lib

macx {
    # macx-clang mkspec включает -fvisibility=hidden глобально —
    # переопределяем чтобы extern "C" функции были видны в dylib
    QMAKE_CXXFLAGS += -fvisibility=default
    QMAKE_CFLAGS   += -fvisibility=default
}

LIBS += -L$$DESTDIR -lqte56_foundation
