/**
 * qte56_mainwin.d — umbrella import (auto-generated by merge_dlls.py).
 * DLL: qte56_mainwin.dll
 */
module qte56_mainwin;

public import
    gen_qmainwindow,
    gen_qmenubar,
    gen_qmenu,
    gen_qaction,
    gen_qtoolbar,
    gen_qtoolbutton,
    gen_qcommandlinkbutton,
    gen_qstatusbar,
    gen_qdockwidget,
    gen_qtoolbox;

