/**
 * qte56_text.d — umbrella import (auto-generated by merge_dlls.py).
 * DLL: qte56_text.dll
 */
module qte56_text;

public import
    gen_qplaintextedit,
    gen_qtextedit,
    gen_qtextbrowser,
    gen_qtextcursor,
    gen_qtextcharformat,
    gen_qtextblockformat,
    gen_qtextblock,
    gen_qsyntaxhighlighter;

