/**
 * qte56_foundation.d — umbrella import (auto-generated by merge_dlls.py).
 * DLL: qte56_foundation.dll
 */
module qte56_foundation;

public import
    gen_qobject,
    gen_qfont,
    gen_qicon,
    gen_qcolor,
    gen_qpixmap,
    gen_qtimer,
    gen_qsettings,
    gen_qclipboard,
    gen_qbuttongroup;

