/**
 * qte56_views.d — umbrella import (auto-generated by merge_dlls.py).
 * DLL: qte56_views.dll
 */
module qte56_views;

public import
    gen_qabstractscrollarea,
    gen_qabstractitemview,
    gen_qscrollarea,
    gen_qlistwidget,
    gen_qtableview,
    gen_qtablewidget,
    gen_qtreeview,
    gen_qtreewidget,
    gen_qheaderview,
    gen_qmdiarea,
    gen_qmdisubwindow;

