/**
 * qte56_widgets.d — umbrella import (auto-generated by merge_dlls.py).
 * DLL: qte56_widgets.dll
 */
module qte56_widgets;

public import
    gen_qwidget,
    gen_qframe,
    gen_qlabel,
    gen_qpushbutton,
    gen_qcheckbox,
    gen_qradiobutton,
    gen_qcombobox,
    gen_qlineedit,
    gen_qspinbox,
    gen_qdoublespinbox,
    gen_qslider,
    gen_qdial,
    gen_qscrollbar,
    gen_qprogressbar,
    gen_qgroupbox,
    gen_qtabwidget,
    gen_qtabbar,
    gen_qlcdnumber,
    gen_qcalendarwidget,
    gen_qlayout,
    gen_qabstractbutton,
    gen_qabstractslider,
    gen_qabstractspinbox,
    gen_qsplitter,
    gen_qstackedwidget,
    gen_qdatetimeedit;

