/**
 * qte56_dialogs.d — umbrella import (auto-generated by merge_dlls.py).
 * DLL: qte56_dialogs.dll
 */
module qte56_dialogs;

public import
    gen_qdialog,
    gen_qmessagebox,
    gen_qfiledialog,
    gen_qinputdialog,
    gen_qfontdialog,
    gen_qcolordialog,
    gen_qprogressdialog;

